# Jekyll configuration

name: mok 개발일지
description: Software Developer

# Url is currently only used only for the RSS feed in feed.xml
url: https://seungchan-mok.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: seungchan mok
copyright: 2020-2021

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: seungchan-mok
  facebook: 'mok0000'
  linkedin:
  instagram: 'mok____'
  rss: feed.xml
  kakaotalk: openchatting

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-158294787-1
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: msc9533
comments: true

permalink: /:year/:month/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

exclude: ['README.md', 
          'LICENSE', 
          'todolist.md',
          '_posts/2020-05-30-icp-matching.md',
          '_posts/2020-09-04-cam-lidar-projection.md',
          '_posts/2021-04-25-remote-vscode-docker.md',
          '_posts/2021-04-09-titanic-knn-tutorial.md']

tipue_search:
  include:
    pages: false
    collections: []
  exclude:
    files: [search.html, index.html, tags.html]
    categories: []
    tags: []

# exclude: ['README.md', 'LICENSE', 'todolist.md']
